
export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
export const UPDATE_PURCHASEABLE = "UPDATE_PURCHASEABLE"

export const RESET_INGREDIENTS = "RESET_INGREDIENTS"

export const ORDER_LOADED = "ORDER_LOADED"
export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED"


export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const AUTH_LOADING = "AUTH_LOADING"
